# Generated by Django 4.2 on 2024-11-20 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='name',
            new_name='username',
        ),
    ]
